version: "3.9"

services:
# Main Auth service db
  postgres:
    image: postgres:16
    container_name: pg-auth
    environment:
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Audit logs postgres db
  postgres-audit:
    image: postgres:16
    container_name: pg-audit
    environment:
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
      POSTGRES_DB: audit_db
    ports:
      - "5434:5432"
    volumes:
      - pg_audit_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit -d audit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Audit logs mongodb db
  mongodb:
    image: mongo:7
    container_name: mongo-audit
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Main Auth service
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "7071:7071"
    environment:
      PORT: 7071
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: audit
      PGPASSWORD: audit
      PGDATABASE: auth_db
    depends_on:
      postgres:
        condition: service_healthy

  # Audit logs postgres service
  audit-logs-postgres:
    build: ./audit-logs-postgres
    container_name: audit-logs-postgres
    ports:
      - "7072:7072"
    environment:
      PORT: 7072
      PGHOST: postgres-audit
      PGPORT: 5432
      PGUSER: audit
      PGPASSWORD: audit
      PGDATABASE: audit_db
    depends_on:
      postgres-audit:
        condition: service_healthy

  # Audit logs mongodb service
  audit-logs-mongodb:
    build: ./audit-logs-mongodb
    container_name: audit-logs-mongodb
    ports:
      - "7073:7073"
    environment:
      PORT: 7073
      MONGODB_URI: mongodb://mongodb:27017
      MONGO_DATABASE: audit_db
    depends_on:
      mongodb:
        condition: service_healthy

  # API Gateway 
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "7070:7070"
    environment:
      GATEWAY_PORT: 7070
      AUTH_URL: http://auth:7071
      AUDIT_POSTGRES_URL: http://audit-logs-postgres:7072
      AUDIT_MONGODB_URL: http://audit-logs-mongodb:7073
    depends_on:
      - auth
      - audit-logs-postgres
      - audit-logs-mongodb
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  pg_auth_data:
  pg_audit_data:
  rabbitmq-data:
